version: "3"
services:
  web:
    build: .
    tty: true
    command: bash -c " python3.7 manage.py makemigrations && python3.7 manage.py migrate && python3.7 manage.py runserver 0.0.0.0:8000"
    container_name: twitter_container
    ports:
    - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
